name: Build, Sign, and Secure

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          IMAGE=ghcr.io/${{ github.repository }}/secure-node-app:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE }}
          format: spdx-json
          output-file: sbom.json

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: 0

      - uses: sigstore/cosign-installer@v3

      - run: |
          if [ "${{ github.actor }}" = "nektos/act" ]; then
            echo "Running locally with act: using local key-pair"
            echo "${{ secrets.COSIGN_KEY }}" > cosign.key
            echo "${{ secrets.COSIGN_PUB }}" > cosign.pub
            cosign sign --key cosign.key ${{ env.IMAGE }}
            cosign verify --key cosign.pub ${{ env.IMAGE }}
          else
            cosign sign --keyless ${{ env.IMAGE }}
          fi

      - name: Generate SLSA Provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
        with:
          base64-subjects: ${{ steps.build.outputs.hashes }}

