name: Build, Sign, and Secure

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/secure-node-app:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .

      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE }}
          format: spdx-json
          output-file: sbom.json

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: 0

      - uses: sigstore/cosign-installer@v3

      - name: Sign container image
        run: |
          cosign sign --yes --keyless ${{ env.IMAGE }}

  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_container_slsa3.yml@v2.0.0
    permissions:
      id-token: write
      contents: read
    with:
      image: ghcr.io/${{ github.repository }}/secure-node-app:${{ github.sha }}
